[workspace]
resolver = "2"
members = ["mukae", "mukae-face",
    "mukae-greetd",
    "mukae-native", "mukae-greeter", "mukae-host", "mukae-lisp", "mukae-spec"]

[workspace.package]
version = "0.1.9"
edition = "2024"
license = "MIT"
repository = "https://github.com/pleme-io/mukae"
rust-version = "1.89"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
